### ISSUE TITLE
About 'wan communication over TCP' in readdocs

### ISSUE THREAD

**Issue by guni9191** [eProsima/DDS-Router#337]
[Readdoc guide](https://eprosima-dds-router.readthedocs.io/en/latest/rst/use_cases/wan_tcp.html#) instructs to use the code below to create docker conatiner
`docker run -it -v <path/to/file>/ddsrouter_net_B.yaml:/ddsrouter_net_B.yaml ubuntu-fastdds-suite:<FastDDS-Version>
`
but to my knowledge, the `--net=host` option should be included to connect external device through WAN. 
Thus I suggest that for those who have followed the guide and did not work try using this option/

**Comment by juanlofer-eprosima** [comment]
Hi @guni9191

You are absolutely right, thanks for pointing this out. We included the argument in the general instructions on how to use Docker images, but missed it in the tutorial... will fix it right away!

Best regards
