### ISSUE TITLE
Repeater using TCP with same domain ids

### ISSUE THREAD

**Issue by CselecT** [eProsima/DDS-Router#373]
Hello, first of all thank you for the detailed examples.
I am trying to create a router network that will connect ros2 nodes that are working in different networks. The basic structure is like [here](https://github.com/eProsima/DDS-Router/blob/main/ddsrouter_test/compose/test_cases/repeater_tcp/compose.yml), however I need to be able to set the same domain ids for the sub and pub edges in different networks. I am aware that we can do this with the repeater using udp, however I need to use tcp. I also know that a local discovery server can help, however I could not integrate a local discovery server to the repeater example. I tried starting the discovery server in router edges, but I could not listen the talker from the other network.
To sum up, I want to create [this](https://github.com/eProsima/DDS-Router/blob/main/ddsrouter_test/compose/test_cases/repeater_tcp/compose.yml) example but with using the same domain ids for the pub_edge_1 and sub_edge_2, using tcp. I would be grateful if you can provide an example or direct me to a possible solution. Thanks!

**Comment by jparisu** [comment]
Hi @CselecT 
As this is a question regarding a particular use case rather than an issue, I transfer it to discussions.
