### ISSUE TITLE
Not configuration file given, using default file DDS_ROUTER_CONFIGURATION.yaml.

### ISSUE THREAD

**Issue by 1776340526** [eProsima/DDS-Router#459]
Hello, I encountered some problems when installing and using DDS Router, and I would like to ask you the following. When I execute the following command, it prompts that there is no yaml file. I don’t see this code in the installed file. Do I need to create this yaml file myself? How can I make the executable file recognize this yaml file?

The following is the code and output:

ros2@ros2:~$ ./DDS-Router/install/ddsrouter_tool/bin/ddsrouter

Not configuration file given, using default file DDS_ROUTER_CONFIGURATION.yaml.

2024-06-26 05:37:24.343 [DDSROUTER_ARGS Error] File 'DDS_ROUTER_CONFIGURATION.yaml' does not exist or it is not accessible. -> Function main

**Comment by juanlofer-eprosima** [comment]
Hi @1776340526 , please have a look at https://github.com/eProsima/DDS-Router/issues/190 .

Best regards

**Comment by 1776340526** [comment]
I understand that I need to add the yaml file when running.But the documentation is not clear.Thanks for your help!
